### PR TITLE
Blog thoughts

### PR DESCRIPTION
**Pull request by bluetech**
Hi,

I read your blog post https://mgattozzi.com/refactor-rust. I thought there were somethings that could be improved as I read it. Here are some commits with proposed change (see commit messages). There are a few more improvements I think can be made, however my time for this had ran out...

Please note: I have no use for github API, this was just for fun. Please feel free to cherry pick, amend, rewrite, drop, clean up etc (no need to preserve authorship).

### CODE REVIEW

**Comment by bluetech** [comment]
Added a couple more commits anyway :)

**Comment by mgattozzi** [comment]
@bluetech Hey just wanted to let you know I've seen this. I'm at RustFest right now and I have a really busy week up ahead so I might not get to this anytime soon but there are a few things I think I will take from here, but I'm not sure just yet what I will. Anyways I just wanted you to know I saw this so thank you :D

**Comment by mgattozzi** [comment]
@bluetech I've been a bit busy this week, with finals and National Guard stuff. I'll be looking into this either late next week or the week after since this is a big change of a pr

**Comment by JuanPotato** [comment]
I know this isn't my PR but I thought I might drop a ping because I came across this project and it looks really nice. Might submit a few PRs of my own

**Comment by mgattozzi** [comment]
@JuanPotato Please do! Mostly it's just implementing more endpoints as the lower level architecture is pretty much complete. Feel free to ask questions in the issue tracker or by email (mgattozzi@gmail.com) if you have any. I'm still personally debating what to take from this PR as it does have some pretty breaking changes in it.

**Comment by mgattozzi** [comment]
Most of this is getting restructured to move towards reqwest and avoid using hyper directly so I'm going to close this.

**Pull request closed without merging**
