### PR TITLE
Client send

### PR DESCRIPTION
**Pull request by mathstuf**

### CODE REVIEW

**Comment by mathstuf** [comment]
Hrm, looks like the `RefCell` needs to be `Mutex` instead…

**Comment by mathstuf** [comment]
Ugh, this just isn't going to work :( . Tokio is being a pain. Is there any reason for using an event loop to just complete a single future instead of using a synchronous API?

**Comment by mathstuf** [comment]
Using `reqwest` would probably be the easiest way to do that. Not sure how well that works with the current design though.

**Comment by mgattozzi** [comment]
@mathstuf the idea was to eventually make this API asynchronous or synchronous based off the user choice (though I never really wrote that down anywhere) I eventually wanted to make a version of the client that worked across threads as well using Arc and Mutex (or something simmilar) at some point. I hadn't really come up with a good design yet given I'd have to figure out the best way to autogenerate the code with the macros.

I'd like to provide the following types of client:
- Synchronous and Non Multithreaded
- Synchronous and Multithreaded
- Asynchronous and Non Multithreaded
- Asynchronous and Multithreaded

This way the user can choose the best one for their needs. For instance if I'm not doing multithreaded code having an `Arc` in the data structure is a bit much when an `Rc` would suffice.

As it stands the code uses Tokio but it acts synchronously due to the use of the `run` function in the `Core` type. Eventually this should allow an `async_execute` or a `sync_execute` function at the user's choice. `reqwest` is nice but I need access to the headers for a lot of the code and some more low level stuff so using Hyper directly is more of what is needed, that and making the request is simple enough that it's not too terrible to do without `reqwest`. Most of that logic was encapsulated in a small part of the code base.

@mathstuf do you need the multithreaded client for your work? I'd be more than happy to work with you and bang out an implementation of it so you can use it especially since it was a planned feature in my head (I just never put it in the issue tracker). A lot of the work had been to get 0.5 to use Tokio to eventually move on to multiple client type, more endpoints, and eventually a simple server to handle webhooks, and code to parse incoming requests. With the new `http` crate I think this last part will be a bit more doable.

Anyways this was a bit of a brain dump but let me know what you're thinking/need and I'm sure we can come up with a good solution :)

**Comment by mathstuf** [comment]
I'll open a new PR for the two typo fixes at the start of this branch.

**Comment by mgattozzi** [comment]
@mathstuf hmmm yeah if you're doing stuff with rayon then you'll need it for sure.

As for the async. Part of the reason I created the `expose_core` method was because it seemed silly to have multiple event loops. I think this is a limiting design of Tokio not creating a way to have single global even loop. It's really one of the only times I think global state would be better in some senses.

Having a future returned seems like a reasonable thing, and letting the user decide what to do with it as you might want to do other things with the response once executed. There's no real clear best way to do this right now. I'd have to spend some time thinking about what to do for this to make it a good design and how to integrate it into the current library.

**Comment by mathstuf** [comment]
> I think this is a limiting design of Tokio not creating a way to have single global even loop.

I think the design (though I'm not sure) is that libraries provide events (`Future` here) and the application sets up the event loop. The problems usually arise from GUI toolkits because they provide their own event loops for convenience and in order to interact, the event loops need exposed. I think this library can get away with not providing an event loop as long as there's also a synchronous call available (`reqwest` seems to do it with a thread pool and would be easier than trying to reimplement it here.).

**Comment by mgattozzi** [comment]
Hmmmm... I see. It might be best to just have it set up the future and have the end user spawn and run the future the way they want too. Urgh but I also like having to not set it up and just let people make calls without it. Even reqwest is moving over to the newer version of hyper soon too so even that won't necessarily be synchronous.

**Comment by mathstuf** [comment]
> Urgh but I also like having to not set it up and just let people make calls without it.

That works when you have exactly zero or one libraries doing this for you. When you have two libraries doing Tokio stuff in your app, the application now needs to unite the two (or more) event loops together somehow.

> Even reqwest is moving over to the newer version of hyper soon too so even that won't necessarily be synchronous.

I hope not. Async isn't free and the ability to have a synchronous API is really nice. It would be a serious regression if it only did async calls IMO… *goes to look if noise needs to be made*

**Comment by mathstuf** [comment]
It looks like there is `reqwest::unstable::async::Client` and `reqwest::Client`, so it appears that the option is there for both styles.

**Comment by mgattozzi** [comment]
It might be best to switch over to this for now. It would solve the issue you're having with the whole Core and make it easier to make things Sync and Send.

**Comment by mathstuf** [comment]
OK, I'll look into converting over to reqwest this week.

**Comment by mgattozzi** [comment]
Awesome! My guess if you'll need to modify the macros to generate the types for Async and NonAsync requests and have Two client types. Or even better just have it be an option when creating the the client type to choose between Sync or Async and you won't need to modify as many things. If you get stuck or don't understand the code please let me know.

**Comment by AlexNPavel** [comment]
So is github-rs moving away from hyper and to reqwest instead? This would actually make it easier to handle GET parameters as mentioned in issue #60  since reqwest has the `parse_with_params` function that simplifies things a lot (https://docs.rs/reqwest/0.7.2/reqwest/struct.Url.html). Hyper, on the other hand, doesn't seem to provide any easy way to do this and it looks like you have to contruct and it looks like you have to construct the entire uri as a str yourself before converting it to a Uri struct.

**Comment by AlexNPavel** [comment]
reqwest also has a `set_query` function that doesn't need the base URL like `parse_with_params`

**Comment by mgattozzi** [comment]
If reqwest can handle everything that github-rs currently needs then yeah that would be fine by me. I don't know the API as well but it seems ergonomics wise it would be a better choice rather than dealing with tokio directly.

**Comment by mathstuf** [comment]
See #70.

**Pull request closed without merging**
