### PR TITLE
Adopt Rustfmt Style (?)

### PR DESCRIPTION
**Pull request by rye**
First, I think the Rustfmt default style is not _that_ far off from what is already used.  Switching to a standardized style (and formatting tool) has one key benefit, which is that all contributors can simply run `cargo fmt` (after installing `rustfmt`, of course) to ensure that their code adheres to the codebase's formatting style.  A step further would be to enable this in CI, and force all PRs to adhere to the style going forward.

So, this PR serves as an idea for what the "default style" might look like.  If certain things are not desirable, please let me know—I initially tried to match the style across all the files with the rustfmt configuration, but quickly realized that there are certain files which are formatted to one style and others which are formatted to other styles.  So, I instead simply set this up to use the defaults.

Feel free to consult [the docs](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md) for any ideas on options to configure away from their defaults.

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
Thanks for this. 

A `rustfmt.toml` isn't needed if you are following the default rustfmt 
Also are you running rustfmt on stable or on nightly? cause things might differ based on that.

**Comment by rye** [comment]
@Dylan-DPC, thanks for taking a look. I am running this on nightly, currently, but it appears that that does not make a difference:

```console
$ cargo +stable fmt
$ git diff
$ cargo +nightly fmt
$ git diff
```

I included the `rustfmt.toml` in case any customizations were wanted. Should I remove it?

**Comment by Dylan-DPC** [comment]
Thanks for checking it. Earlier they used to be differences, but i guess there are none since rustfmt was stabilised. 

Yeah, I know the use of the file but since we are sticking to default configuration, there is no point in keeping it.

**Comment by rye** [comment]
Okay, I have removed `.rustfmt.toml`.

**Comment by Dylan-DPC** [comment]
THanks

**Pull request merged**
