### PR TITLE
repos: add support for contents

### PR DESCRIPTION
**Pull request by crawford**
The base functionality works, but I'm not sure how to add support for the optional GET parameter "ref".

### CODE REVIEW

**Comment by mgattozzi** [comment]
My recommendation is to add a `Parameters` type in src/lib.rs that can be turned into an `Executor` for endpoints that can have parameters add the ability to transition to a parameters type taking a `Vec<(&str, &str)>` and have it parse the [url with params](https://slack-rs.github.io/slack-rs/reqwest/struct.Url.html#method.parse_with_params). The library is using reqwest now so this should be easier

**Comment by crawford** [comment]
I don't quite follow. How is the user to use the `Parameters` type? Something like this:

```rust
client
    .get()
    .repos()
    .owner(owner)
    .repo(repo)
    .contents()
    .path("file.txt")
    .parameters(vec![("ref", "master")])
    .execute()
```

I was thinking about extending the macros to allow parameters to be annotated. The result would look like:

```
client
    .get()
    .repos()
    .owner(owner)
    .repo(repo)
    .contents()
    .path("file.txt")
    .ref("master")
    .execute()
```

In this case, `ref()` is the parameter to `/repos/:owner/:repo/contents/:path`.

**Comment by mgattozzi** [comment]
Yeah the first one is what I was thinking but the other way would be fine as well if you want to expand out the macro to work with it..

**Comment by crawford** [comment]
(I rolled back the reqwests change for now so I could test this.)

I ended up going with the latter. Let me know what you think of the syntax. It seems to work pretty well, but I haven't really pushed all of the edge cases yet.

**Comment by crawford** [comment]
I also took the opportunity to clean up the design docs slightly now that I understand how the macros work. I hope the content is accurate.

**Comment by mgattozzi** [comment]
These are looking good! Thanks for cleaning up the macros and design docs. Once we get the fix in for reqwest can you rebase off of master so that we can avoid using hyper?

**Comment by crawford** [comment]
Yep. That shouldn't be too much trouble. I'll hang tight.

**Comment by mgattozzi** [comment]
@crawford changes from the reqwest failure have been reverted. Please rebase off of master and we can get this merged if it's good to go on your end :)

**Comment by crawford** [comment]
Thanks!

**Comment by crawford** [comment]
I've got one more patch that builds on this one a bit. I'll put that up once this merges to avoid any rebasing.

**Comment by mgattozzi** [comment]
I see you need this one as a tagged release so once we get this stuff in I'll do a minor version release for you. Sorry if it's made work a bit more hectic! I know how hard it can be. I had to fork something for work just the other day and had to make it a git dependency 😅

**Comment by mgattozzi** [comment]
Are you saying this is good to merge now but a separate PR is incoming?

**Comment by crawford** [comment]
Yes. This one is good as is.

**Comment by crawford** [comment]
Oh, if you could cut a release after the next PR (it's a little bigger), that would be awesome. We are working on https://github.com/coreos/tailor, which does mechanical verification of pull requests of our numerous repos.

**Comment by mgattozzi** [comment]
@crawford awesome! It's cool to see this code being used as part of such a large project. Send in that PR whenever you have the time

**Pull request merged**
