### PR TITLE
DELETE for Gists done.

### PR DESCRIPTION
**Pull request by Henning-K**
crossed off endpoints
Partial fix for https://github.com/mgattozzi/github-rs/issues/89

### CODE REVIEW

**Comment by mgattozzi** [comment]
Hey @Henning-K do you mind rebasing and squashing these commits? Also could you change the commit title to follow an imperative tone? Something like: "Added DELETE endpoints for Gists" should be perfect! Once you do I can merge this :D

**Comment by Henning-K** [comment]
Wow, that was the first time I used git rebase and it just felt dirty...
But now everything should be in order, right?

**Comment by mgattozzi** [comment]
@Henning-K dirty? It's a great tool for making a whole bunch of in progress commits than slamming them all into one or cleaning them up. `git rebase -i` is super nice (unless you have like a 4 way merge conflict to deal with :( )

**Comment by mgattozzi** [comment]
But yeah this is all in order now! I'm just going to let it pass the CI and merge all these. Thanks for all your hard work @Henning-K!

**Pull request merged**
