### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by Dylan-DPC**
References #141 

`cargo test` added to build script

### CODE REVIEW

**Comment by Arzte** [comment]
This should probably be fixed so that the tests can be ran. https://travis-ci.org/mgattozzi/github-rs/jobs/348905974#L623

**Comment by mgattozzi** [comment]
Hmmm weird. It should be using the encrypted one in the repo? Let me check things on my end since I have access to fix this. Maybe travis changed something or it's not put in properly.

**Comment by mgattozzi** [comment]
Oh okay I see it's not even in the script for whatever reason. I'll fix this up and send it in. It'll be a token from my GitHub bot @thearesia

**Comment by mgattozzi** [comment]
This is going to run a ton of tests across all the different versions. We'll definitely need to address this issue. I'll need to send an email to GitHub about the rate limiting.

**Comment by mgattozzi** [comment]
@Dylan-DPC the token works now but it's failing on a graphql-test it seems.

**Comment by Dylan-DPC** [comment]
Yeah. we coud limit it to run only on the nightly versions. A mocked github API will take some time, that's the problem.

**Comment by mgattozzi** [comment]
@Dylan-DPC I would say limit it to stable. That's the only one we guarantee support for now. It used to be nightly only but not anymore.

**Comment by Dylan-DPC** [comment]
The reason i suggested nightly is that because if it works on nightly generally it would mean that it works on stable right?

**Comment by mgattozzi** [comment]
@Dylan-DPC you are correct, but running beta and nightly is for a different purpose. Here's a more thorough break down as to why stable:

- We want to build nightly and beta every PR because we want to check if an upcoming compiler change will cause the build to fail
- If it doesn't fail the build then that means the code is essentially the same.
- This means we can test on stable and expect it to behave the same way on beta and nightly
- What if there is a regression on nightly though? We use that for the tests, but beta and nightly builds are optional or they should be (I just checked and realized they weren't). If they failed it shouldn't block everything. Stable is our guarantee and if it passes on stable and runs tests on stable then we don't need to block someone's PR on a breaking change for Beta and Nightly. Those can be addressed in later PRs.

Summary:
- Beta/Nightly should be optional as they're to test build fails
- Stable should be used for building and tests as this is for library functionality and our guarantee that the library works on stable.

**Comment by Dylan-DPC** [comment]
Oh fair enough. Yeah then i'm fine with keeping it on stable.

**Comment by mgattozzi** [comment]
@Dylan-DPC cool! :D Let's get the graphql test fixed and put the other two channels on optional for now and have stable be the only one to run tests.

**Comment by mgattozzi** [comment]
@Dylan-DPC I mean you could still keep them just put it under allow_failures :D
https://docs.travis-ci.com/user/languages/rust/

**Comment by Dylan-DPC** [comment]
Ah my bad. I thought you didn't want the build to take that long and run on each channel

**Comment by mgattozzi** [comment]
Ah no I like having it check anyways. It's not like this repo is high activity so it's not a big deal to me to get some sanity checks in there! :D

**Comment by Dylan-DPC** [comment]
How do you `allow_failures` multiple channels? comma-seperated?

**Comment by mgattozzi** [comment]
Yeah I'll do it :)

**Comment by Arzte** [comment]
You can make ``allow_failures`` not to be counted for the build to be finished with ``fast_finish=true``. Travis will then complete the build even if ``allow_failures`` builds are finished.

**Comment by Dylan-DPC** [comment]
thanks @Arzte i have made the change

**Comment by mgattozzi** [comment]
With the fast_finish that seems like this will be good to merge. Only blocker is that graphql test. My guess is the token maybe? I haven't dug too much into it.

**Comment by Dylan-DPC** [comment]
You need to create the token thing for the graphql tests as well right?

**Comment by mgattozzi** [comment]
You could just use the same one. I think I can just have it cp the file to the directory in the script hold on.

**Comment by mgattozzi** [comment]
Nice it worked let's get this squashed and merged

**Pull request merged**
