### PR TITLE
repos: add new get and post endpoints

### PR DESCRIPTION
**Pull request by AlexNPavel**
This adds a bunch of endpoints that are being used in a project I am
working on. You can see what endpoints were added in the
docs/endpoints.md file.

I did not add any endpoints with "ref" as that is a reserved keyword in 
rust and cannot be used directly as a function (that may have to be
worked around eventually).

### CODE REVIEW

**Comment by mgattozzi** [comment]
Yeah I'll have to come up with a way to get ref to work somehow in the macro at some point. In the meantime the [custom endpoint](https://docs.rs/github-rs/0.5.0/github_rs/client/struct.GetQueryBuilder.html#method.custom_endpoint) can be used if you have need of it.

@AlexNPavel Have you tested and used these yourself to make sure they work? (I'm still working on a good way to test all these considering github rate limits things and `cargo test` runs in parallel not serial)

Another question not related to the PR itself, I was wondering how easy it was for you to work with the macros/what could be improved for usability sake as I'm still trying to find a good balance between maintainability for contributors and usability for the end user

**Comment by AlexNPavel** [comment]
I just tested the couple of endpoints I haven't been using and everything seems to work fine (merge is a bit weird. The answer is the status code: 204 for merged, 404 for not merged, but that's apparently how the API is supposed to work).

In terms of the macros it was all good. It took less than half an hour to get used to the way that endpoints are declared. Maybe some very basic docs regarding how to add new endpoints could be useful, but it's not difficult to figure out just by looking at how other endpoints are implemented.

**Comment by mgattozzi** [comment]
@AlexNPavel I need to update the docs. There's an issue for it in #43. Alright this looks good to me!

**Comment by mgattozzi** [comment]
Thanks again @AlexNPavel! I'll push a minor update for you now :)

**Pull request merged**
