### PR TITLE
macros: introduce executor trait

### PR DESCRIPTION
**Pull request by crawford**
This changes the macro structure so that instead of using from! and
impl_macro! to create the execute() method, it's done by invoking the
exec! macro. This allows all types with the execute() method to
implement the Executor trait. By implementing a trait, it allows
consuming code to easily pass queries around without having to execute
them up front.

@mgattozzi This is a much more invasive change, but I think it simplifies the macros a bit and having the Executor trait is pretty handy. I threw in a new example to show how I'm using the new functionality.

### CODE REVIEW

**Comment by mgattozzi** [comment]
This is to prevent cloning cores and things then and passing those types around correct?

**Comment by crawford** [comment]
It's so that you can pass an executor (implemented by all exec! types) into a function. This allows you to write a generic wrapper for all requests. The example I added shows how to extend the executor trait in a similar fashion.

**Comment by mgattozzi** [comment]
Ah got it. So if you use `execute()` as is today it won't change anything (beyond needing to import the trait), but you can use it in another trait to handle how you want to deal with the requests you get back correct? If so that should be fine, it'll need to make this a 0.6 release considering this would break existing code.

**Comment by crawford** [comment]
Correct. All requests result in an object that implements Executor, so you can use that to generically operate on requests. Tagging 0.6 makes sense, as you said.

**Comment by mgattozzi** [comment]
Awesome! I'm just going to go through and make sure everything you've removed as an executor now has the trait implemented then I'll merge it!

**Comment by mgattozzi** [comment]
Alright @crawford took me a bit but this looks good. new_type!() macro wasn't changed so I only had to double check the other ones. This looks great to me! In the future maybe we could expand exec!() to act like new type so it can just have a list of types in it? It would help with readability I think. Anyways I'm going to merge this and cut a release! Thanks for the hard work of improving the library. I really appreciate it.

**Pull request merged**
